title: Texture Theme
author: GitHub User
email: vrdd21@naver.com
description: > # this means to ignore newlines until "show_exerpts:"
  I am a graduate student of Seoul National University from 2020.03.01. If you find any bugs in my codes, please feel free to tell me by using disqus.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Kim Ji Soo
  tagline: Developer.
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: 
    github:  vrdd21
    linkedIn: 
    rss: rss
  disqus_shortname: chats
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
